### ISSUE TITLE
URL compulsary?

### ISSUE THREAD

**Issue by Logmytech** [codelucas/flask_reddit#11]
Sharing a link with a text post seems to be compulsary.

How do I remove it. I'm getting an `That is not a valid link url!`
 when I try to post without a link

**Comment by codelucas** [comment]
This is by design @Logmytech - this entire project was meant to give people sample code on how to close large web-apps like reddit, I did not stress the precise details. If you feel the need to change this logic you can do it yourself 

(there may be more details involved, I haven't touched this code in a long time)

**Comment by Logmytech** [comment]
Thank you for the reply. So you are active and accept pull requests.

I thought you were inactive and the project was dead.
