### ISSUE TITLE
Require Link?

### ISSUE THREAD

**Issue by RoyceWhitaker** [codelucas/flask_reddit#4]
Why does the demo site require you to enter a link?

Is there an option to enable just text post?

Thanks!

**Comment by Logmytech** [comment]
I have the same issue and accidentally opened a new issue.

Have you solved this?

**Comment by codelucas** [comment]
This is by design @Logmytech - this entire project was meant to give people sample code on how to close large web-apps like reddit, I did not stress the precise details. If you feel the need to change this logic you can do it yourself easily at: https://github.com/codelucas/flask_reddit/blob/master/flask_reddit/threads/views.py#L25-L40

(there may be more details involved, I haven't touched this code in a long time)
